apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: context-foundation-staging

bases:
  - ../../

patchesStrategicMerge:
  - namespace-patch.yaml

configMapGenerator:
  - name: api-config
    namespace: context-foundation-staging
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=DEBUG

replicas:
  - name: context-api
    count: 2

images:
  - name: ghcr.io/dpdpdpdp0987/context-api
    newTag: staging

commonLabels:
  environment: staging
